### ISSUE TITLE
Invalid Add-on Repository

### ISSUE THREAD

**Issue by pashdown** [LordMike/hass-addons#3]
This fails with "Invalid Add-on Repository" on a current version of supervisor.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/175150/139539891-cf2506e6-7f9c-43ae-8bfc-24b98a66cc56.png">

**Comment by LordMike** [comment]
Can you get more details, logs for example?

I'm probably missing some new property.

**Comment by pashdown** [comment]
> Can you get more details, logs for example?
> 
> I'm probably missing some new property.

Happy to try if you can point me to instruction on how to do so.  Nothing appears in the supervisor logs as is.

**Comment by LordMike** [comment]
I have next to no experience with the Hassio part of HASS...

Buut, I'm guessing if you call this service, you can raise the log level: https://www.home-assistant.io/integrations/logger/#service-set_default_level

> service: logger.set_default_level
> data:
>  level: info

I don't think it'll give anything new - an invalid repository would be an "error" or "warning".. so it should have appeared..

You're checking the system logs too? (Configuration -> Logs)

**Comment by pashdown** [comment]
Went another route on implementing this.
